[versions]
agp = "8.13.2"
kotlin = "2.2.21"
googleMobileAds = "25.5.0"

[libraries]
google-mobile-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "googleMobileAds" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
