//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models

@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal open class DummyResponse : Comparable<Any?>
{
    var id: Int
    var status: ResponseStatus
    var headers: java.util.ArrayList<Header>
    var body: String
    var elapsedMs: Double
    var cached: Boolean

    @Transient open var fbeType: Long = 3

    constructor(id: Int = 0, status: ResponseStatus = ResponseStatus(), headers: java.util.ArrayList<Header> = java.util.ArrayList(), body: String = "", elapsedMs: Double = 0.0, cached: Boolean = false)
    {
        this.id = id
        this.status = status
        this.headers = headers
        this.body = body
        this.elapsedMs = elapsedMs
        this.cached = cached
    }

    @Suppress("UNUSED_PARAMETER")
    constructor(other: DummyResponse)
    {
        this.id = other.id
        this.status = other.status
        this.headers = other.headers
        this.body = other.body
        this.elapsedMs = other.elapsedMs
        this.cached = other.cached
    }

    open fun clone(): DummyResponse
    {
        // Serialize the struct to the FBE stream
        val writer = com.revenuecat.purchases.fbepoc.models.fbe.DummyResponseModel()
        writer.serialize(this)

        // Deserialize the struct from the FBE stream
        val reader = com.revenuecat.purchases.fbepoc.models.fbe.DummyResponseModel()
        reader.attach(writer.buffer)
        return reader.deserialize()
    }

    override fun compareTo(other: Any?): Int
    {
        if (other == null)
            return -1

        if (!DummyResponse::class.java.isAssignableFrom(other.javaClass))
            return -1

        @Suppress("UNUSED_VARIABLE")
        val obj = other as DummyResponse? ?: return -1

        @Suppress("VARIABLE_WITH_REDUNDANT_INITIALIZER", "CanBeVal", "UnnecessaryVariable")
        var result = 0
        result = id.compareTo(obj.id)
        if (result != 0)
            return result
        return result
    }

    override fun equals(other: Any?): Boolean
    {
        if (other == null)
            return false

        if (!DummyResponse::class.java.isAssignableFrom(other.javaClass))
            return false

        @Suppress("UNUSED_VARIABLE")
        val obj = other as DummyResponse? ?: return false

        if (id != obj.id)
            return false
        return true
    }

    override fun hashCode(): Int
    {
        @Suppress("CanBeVal", "UnnecessaryVariable")
        var hash = 17
        hash = hash * 31 + id.hashCode()
        return hash
    }

    override fun toString(): String
    {
        val sb = StringBuilder()
        sb.append("DummyResponse(")
        sb.append("id="); sb.append(id)
        sb.append(",status="); sb.append(status)
        @Suppress("ConstantConditionIf")
        if (true)
        {
            var first = true
            sb.append(",headers=[").append(headers.size).append("][")
            for (item in headers)
            {
                sb.append(if (first) "" else ",").append(item)
                first = false
            }
            sb.append("]")
        }
        sb.append(",body="); sb.append("\"").append(body).append("\"")
        sb.append(",elapsedMs="); sb.append(elapsedMs)
        sb.append(",cached="); sb.append(if (cached) "true" else "false")
        sb.append(")")
        return sb.toString()
    }

    companion object
    {
        const val fbeTypeConst: Long = 3
    }
}
