//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models

@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal open class DummyRequest : Comparable<Any?>
{
    var id: Int
    var method: HttpMethod
    var path: String
    var headers: java.util.ArrayList<Header>
    var body: String?
    var createdAt: Long

    @Transient open var fbeType: Long = 2

    constructor(id: Int = 0, method: HttpMethod = HttpMethod(), path: String = "", headers: java.util.ArrayList<Header> = java.util.ArrayList(), body: String? = null, createdAt: Long = 0L)
    {
        this.id = id
        this.method = method
        this.path = path
        this.headers = headers
        this.body = body
        this.createdAt = createdAt
    }

    @Suppress("UNUSED_PARAMETER")
    constructor(other: DummyRequest)
    {
        this.id = other.id
        this.method = other.method
        this.path = other.path
        this.headers = other.headers
        this.body = other.body
        this.createdAt = other.createdAt
    }

    open fun clone(): DummyRequest
    {
        // Serialize the struct to the FBE stream
        val writer = com.revenuecat.purchases.fbepoc.models.fbe.DummyRequestModel()
        writer.serialize(this)

        // Deserialize the struct from the FBE stream
        val reader = com.revenuecat.purchases.fbepoc.models.fbe.DummyRequestModel()
        reader.attach(writer.buffer)
        return reader.deserialize()
    }

    override fun compareTo(other: Any?): Int
    {
        if (other == null)
            return -1

        if (!DummyRequest::class.java.isAssignableFrom(other.javaClass))
            return -1

        @Suppress("UNUSED_VARIABLE")
        val obj = other as DummyRequest? ?: return -1

        @Suppress("VARIABLE_WITH_REDUNDANT_INITIALIZER", "CanBeVal", "UnnecessaryVariable")
        var result = 0
        result = id.compareTo(obj.id)
        if (result != 0)
            return result
        return result
    }

    override fun equals(other: Any?): Boolean
    {
        if (other == null)
            return false

        if (!DummyRequest::class.java.isAssignableFrom(other.javaClass))
            return false

        @Suppress("UNUSED_VARIABLE")
        val obj = other as DummyRequest? ?: return false

        if (id != obj.id)
            return false
        return true
    }

    override fun hashCode(): Int
    {
        @Suppress("CanBeVal", "UnnecessaryVariable")
        var hash = 17
        hash = hash * 31 + id.hashCode()
        return hash
    }

    override fun toString(): String
    {
        val sb = StringBuilder()
        sb.append("DummyRequest(")
        sb.append("id="); sb.append(id)
        sb.append(",method="); sb.append(method)
        sb.append(",path="); sb.append("\"").append(path).append("\"")
        @Suppress("ConstantConditionIf")
        if (true)
        {
            var first = true
            sb.append(",headers=[").append(headers.size).append("][")
            for (item in headers)
            {
                sb.append(if (first) "" else ",").append(item)
                first = false
            }
            sb.append("]")
        }
        sb.append(",body="); if (body != null) sb.append("\"").append(body!!).append("\""); else sb.append("null")
        sb.append(",createdAt="); sb.append(createdAt)
        sb.append(")")
        return sb.toString()
    }

    companion object
    {
        const val fbeTypeConst: Long = 2
    }
}
