//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models

@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal open class Header : Comparable<Any?>
{
    var name: String
    var value: String

    @Transient open var fbeType: Long = 1

    constructor(name: String = "", value: String = "")
    {
        this.name = name
        this.value = value
    }

    @Suppress("UNUSED_PARAMETER")
    constructor(other: Header)
    {
        this.name = other.name
        this.value = other.value
    }

    open fun clone(): Header
    {
        // Serialize the struct to the FBE stream
        val writer = com.revenuecat.purchases.fbepoc.models.fbe.HeaderModel()
        writer.serialize(this)

        // Deserialize the struct from the FBE stream
        val reader = com.revenuecat.purchases.fbepoc.models.fbe.HeaderModel()
        reader.attach(writer.buffer)
        return reader.deserialize()
    }

    override fun compareTo(other: Any?): Int
    {
        if (other == null)
            return -1

        if (!Header::class.java.isAssignableFrom(other.javaClass))
            return -1

        @Suppress("UNUSED_VARIABLE")
        val obj = other as Header? ?: return -1

        @Suppress("VARIABLE_WITH_REDUNDANT_INITIALIZER", "CanBeVal", "UnnecessaryVariable")
        var result = 0
        return result
    }

    override fun equals(other: Any?): Boolean
    {
        if (other == null)
            return false

        if (!Header::class.java.isAssignableFrom(other.javaClass))
            return false

        @Suppress("UNUSED_VARIABLE")
        val obj = other as Header? ?: return false

        return true
    }

    override fun hashCode(): Int
    {
        @Suppress("CanBeVal", "UnnecessaryVariable")
        var hash = 17
        return hash
    }

    override fun toString(): String
    {
        val sb = StringBuilder()
        sb.append("Header(")
        sb.append("name="); sb.append("\"").append(name).append("\"")
        sb.append(",value="); sb.append("\"").append(value).append("\"")
        sb.append(")")
        return sb.toString()
    }

    companion object
    {
        const val fbeTypeConst: Long = 1
    }
}
