//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models

@Suppress("EnumEntryName", "MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal enum class HttpMethodEnum
{
    get(0 + 0)
    , post(0 + 1)
    , put(0 + 2)
    , delete(0 + 3)
    ;

    var raw: Byte = 0
        private set

    constructor(value: Byte) { this.raw = value.toByte() }
    constructor(value: Short) { this.raw = value.toByte() }
    constructor(value: Int) { this.raw = value.toByte() }
    constructor(value: Long) { this.raw = value.toByte() }
    constructor(value: HttpMethodEnum) { this.raw = value.raw }

    override fun toString(): String
    {
        if (this == get) return "get"
        if (this == post) return "post"
        if (this == put) return "put"
        if (this == delete) return "delete"
        return "<unknown>"
    }

    companion object
    {
        private val mapping = java.util.HashMap<Byte, HttpMethodEnum>()

        init
        {
            for (value in HttpMethodEnum.values())
                mapping[value.raw] = value
        }

        fun mapValue(value: Byte): HttpMethodEnum? { return mapping[value] }
    }
}
