//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models

@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal class HttpMethod : Comparable<HttpMethod>
{
    companion object
    {
        val get = HttpMethod(HttpMethodEnum.get)
        val post = HttpMethod(HttpMethodEnum.post)
        val put = HttpMethod(HttpMethodEnum.put)
        val delete = HttpMethod(HttpMethodEnum.delete)
    }

    var value: HttpMethodEnum? = HttpMethodEnum.values()[0]
        private set

    val raw: Byte
        get() = value!!.raw

    constructor()
    constructor(value: Byte) { setEnum(value) }
    constructor(value: HttpMethodEnum) { setEnum(value) }
    constructor(value: HttpMethod) { setEnum(value) }

    fun setDefault() { setEnum(0.toByte()) }

    fun setEnum(value: Byte) { this.value = HttpMethodEnum.mapValue(value) }
    fun setEnum(value: HttpMethodEnum) { this.value = value }
    fun setEnum(value: HttpMethod) { this.value = value.value }

    override fun compareTo(other: HttpMethod): Int
    {
        if (value == null)
            return -1
        if (other.value == null)
            return 1
        return (value!!.raw - other.value!!.raw).toInt()
    }

    override fun equals(other: Any?): Boolean
    {
        if (other == null)
            return false

        if (!HttpMethod::class.java.isAssignableFrom(other.javaClass))
            return false

        val enm = other as HttpMethod? ?: return false

        if (enm.value == null)
            return false
        if (value!!.raw != enm.value!!.raw)
            return false
        return true
    }

    override fun hashCode(): Int
    {
        var hash = 17
        hash = hash * 31 + if (value != null) value!!.hashCode() else 0
        return hash
    }

    override fun toString(): String
    {
        return if (value != null) value!!.toString() else "<unknown>"
    }
}
