//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models

@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal class ResponseStatus : Comparable<ResponseStatus>
{
    companion object
    {
        val ok = ResponseStatus(ResponseStatusEnum.ok)
        val created = ResponseStatus(ResponseStatusEnum.created)
        val bad_request = ResponseStatus(ResponseStatusEnum.bad_request)
        val not_found = ResponseStatus(ResponseStatusEnum.not_found)
        val server_error = ResponseStatus(ResponseStatusEnum.server_error)
    }

    var value: ResponseStatusEnum? = ResponseStatusEnum.values()[0]
        private set

    val raw: Int
        get() = value!!.raw

    constructor()
    constructor(value: Int) { setEnum(value) }
    constructor(value: ResponseStatusEnum) { setEnum(value) }
    constructor(value: ResponseStatus) { setEnum(value) }

    fun setDefault() { setEnum(0.toInt()) }

    fun setEnum(value: Int) { this.value = ResponseStatusEnum.mapValue(value) }
    fun setEnum(value: ResponseStatusEnum) { this.value = value }
    fun setEnum(value: ResponseStatus) { this.value = value.value }

    override fun compareTo(other: ResponseStatus): Int
    {
        if (value == null)
            return -1
        if (other.value == null)
            return 1
        return (value!!.raw - other.value!!.raw).toInt()
    }

    override fun equals(other: Any?): Boolean
    {
        if (other == null)
            return false

        if (!ResponseStatus::class.java.isAssignableFrom(other.javaClass))
            return false

        val enm = other as ResponseStatus? ?: return false

        if (enm.value == null)
            return false
        if (value!!.raw != enm.value!!.raw)
            return false
        return true
    }

    override fun hashCode(): Int
    {
        var hash = 17
        hash = hash * 31 + if (value != null) value!!.hashCode() else 0
        return hash
    }

    override fun toString(): String
    {
        return if (value != null) value!!.toString() else "<unknown>"
    }
}
