//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models

@Suppress("EnumEntryName", "MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal enum class ResponseStatusEnum
{
    ok(200 + 0)
    , created(201 + 0)
    , bad_request(400 + 0)
    , not_found(404 + 0)
    , server_error(500 + 0)
    ;

    var raw: Int = 0
        private set

    constructor(value: Byte) { this.raw = value.toInt() }
    constructor(value: Short) { this.raw = value.toInt() }
    constructor(value: Int) { this.raw = value.toInt() }
    constructor(value: Long) { this.raw = value.toInt() }
    constructor(value: ResponseStatusEnum) { this.raw = value.raw }

    override fun toString(): String
    {
        if (this == ok) return "ok"
        if (this == created) return "created"
        if (this == bad_request) return "bad_request"
        if (this == not_found) return "not_found"
        if (this == server_error) return "server_error"
        return "<unknown>"
    }

    companion object
    {
        private val mapping = java.util.HashMap<Int, ResponseStatusEnum>()

        init
        {
            for (value in ResponseStatusEnum.values())
                mapping[value.raw] = value
        }

        fun mapValue(value: Int): ResponseStatusEnum? { return mapping[value] }
    }
}
