//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.payload

@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods")
internal open class Payload : Comparable<Any?>
{
    var config: ByteArray
    var blobs: java.util.TreeMap<ByteArray, ByteArray>

    @Transient open var fbeType: Long = 1

    constructor(config: ByteArray = ByteArray(0), blobs: java.util.TreeMap<ByteArray, ByteArray> = java.util.TreeMap())
    {
        this.config = config
        this.blobs = blobs
    }

    @Suppress("UNUSED_PARAMETER")
    constructor(other: Payload)
    {
        this.config = other.config
        this.blobs = other.blobs
    }

    open fun clone(): Payload
    {
        // Serialize the struct to the FBE stream
        val writer = com.revenuecat.purchases.fbepoc.payload.fbe.PayloadModel()
        writer.serialize(this)

        // Deserialize the struct from the FBE stream
        val reader = com.revenuecat.purchases.fbepoc.payload.fbe.PayloadModel()
        reader.attach(writer.buffer)
        return reader.deserialize()
    }

    override fun compareTo(other: Any?): Int
    {
        if (other == null)
            return -1

        if (!Payload::class.java.isAssignableFrom(other.javaClass))
            return -1

        @Suppress("UNUSED_VARIABLE")
        val obj = other as Payload? ?: return -1

        @Suppress("VARIABLE_WITH_REDUNDANT_INITIALIZER", "CanBeVal", "UnnecessaryVariable")
        var result = 0
        return result
    }

    override fun equals(other: Any?): Boolean
    {
        if (other == null)
            return false

        if (!Payload::class.java.isAssignableFrom(other.javaClass))
            return false

        @Suppress("UNUSED_VARIABLE")
        val obj = other as Payload? ?: return false

        return true
    }

    override fun hashCode(): Int
    {
        @Suppress("CanBeVal", "UnnecessaryVariable")
        var hash = 17
        return hash
    }

    override fun toString(): String
    {
        val sb = StringBuilder()
        sb.append("Payload(")
        sb.append("config="); sb.append("bytes[").append(config.size).append("]")
        @Suppress("ConstantConditionIf")
        if (true)
        {
            var first = true
            sb.append(",blobs=[").append(blobs.size).append("]<{")
            for (item in blobs.entries)
            {
                sb.append(if (first) "" else ",").append("bytes[").append(item.key.size).append("]")
                sb.append("->")
                sb.append("bytes[").append(item.value.size).append("]")
                first = false
            }
            sb.append("}>")
        }
        sb.append(")")
        return sb.toString()
    }

    companion object
    {
        const val fbeTypeConst: Long = 1
    }
}
