#!/bin/sh


./gradlew detekt -q
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ detekt failed, running detektAll for you..."

  ./gradlew detektAll -q

  echo "Formatting done, please try your commit again!"
  exit $EXIT_CODE
fi


./gradlew metalavaCheckCompatibilityDefaultsRelease -q
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ metalava for defaults flavor failed, running it for you..."

  ./gradlew metalavaCheckCompatibilityDefaultsRelease -q

  echo "API dump done, please check the results and then try your commit again!"
  exit $EXIT_CODE
fi


./gradlew metalavaCheckCompatibilityCustomEntitlementComputationRelease -q
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ metalava for custom entitlement flavor failed, running it for you..."

  ./gradlew metalavaCheckCompatibilityCustomEntitlementComputationRelease -q

  echo "API dump done, please check the results and then try your commit again!"
  exit $EXIT_CODE
fi

exit 0