x# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

gradle_file_path = "library.gradle"

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Increment build number"
  lane :bump do |options|
    new_version = options[:version]
    fail ArgumentError, "missing version" unless new_version
    previous_version = android_get_version_name(gradle_file: gradle_file_path)
    android_set_version_name(version_name: new_version, gradle_file: gradle_file_path)
    increment_version_in(previous_version, new_version, '../common/src/main/java/com/revenuecat/purchases/common/Config.kt')
    increment_version_in(previous_version, new_version, '../gradle.properties')
  end

  desc "Increment build number and update changelog"
  lane :bump_and_update_changelog do |options|
    bump(options)
    attach_changelog_to_main(options)
  end

  desc "Tag release version with latest if necessary"
  lane :tag_release_with_latest_if_needed do |options|
    release_version = options[:release_version]
    puts "Release version is #{release_version}"

    sh("git", "checkout", "tags/latest")
    latest_version = android_get_version_name(gradle_file: gradle_file_path)
    puts "Latest version is #{latest_version}"

    # We assume there's already a tag for the version we are tagging as latest
    sh("git", "checkout", release_version)

    unless Gem::Version.new(release_version) > Gem::Version.new(latest_version)
      puts "There's a more recent version. Skipping tagging."
      next
    end
    latest_version_commit = sh("git", "rev-list", "--tags=#{release_version}*", "--max-count=1").chomp
    puts "Tagging #{release_version}, with commit #{latest_version_commit} with latest"

    add_git_tag(
      tag: "latest",
      force: true,
      grouping: "releases",
      commit: latest_version_commit
    )
    push_git_tags(
      tag: "latest",
      force: true
    )
  end

  desc "Make github release"
  lane :github_release do |options|
    release_version = options[:version]
    fail ArgumentError, "missing version" unless release_version

    begin
      changelog = File.read("../CHANGELOG.latest.md")
    rescue
      fail "please add a CHANGELOG.latest.md file before calling this lane"
    end

    set_github_release(
      repository_name: "revenuecat/purchases-android",
      api_token: ENV["GITHUB_TOKEN"],
      name: release_version,
      tag_name: "#{release_version}",
      description: changelog,
      commitish: "main",
      upload_assets: []
    )

    tag_release_with_latest_if_needed(release_version: release_version)
  end

  desc "Upload and close a release"
  lane :deploy do |options|
    version = android_get_version_name(gradle_file: gradle_file_path)
    gradleProperties = {
      "signing.keyId" => ENV['GPG_SIGNING_KEY_ID_NEW'],
      "signing.password" => ENV['GPG_SIGNING_KEY_PW_NEW'],
      "signing.secretKeyRingFile" => "/home/circleci/.gnupg/secring.gpg",
      "mavenCentralUsername" => ENV['SONATYPE_NEXUS_TOKEN_USERNAME'],
      "mavenCentralPassword" => ENV['SONATYPE_NEXUS_TOKEN_PASSWORD'],
      "RELEASE_SIGNING_ENABLED" => true
    }
    puts "Deploying #{version}"
    gradle(
      tasks: [
        "androidSourcesJar", "androidJavadocJar", "publish --no-daemon --no-parallel"
      ],
      properties: gradleProperties
    )
    unless is_snapshot_version?(version)
      gradle(
        tasks: [
          "closeAndReleaseRepository"
        ],
        properties: gradleProperties
      )
      github_release(version: version)
    end
  end

  desc "Upload a snapshot release"
  lane :deploy_snapshot do |options|
    version = android_get_version_name(gradle_file: gradle_file_path)
    deploy if is_snapshot_version?(version)
  end

  desc "Prepare next version"
  lane :prepare_next_version do |options|
    current_version_number = android_get_version_name(gradle_file: gradle_file_path)
    major, minor, _ = current_version_number.split('.')
    next_version = "#{major}.#{minor.to_i + 1}.0"
    next_version_snapshot = "#{next_version}-SNAPSHOT"

    branch_name = "bump/#{next_version_snapshot}"
    sh("git", "checkout", "-b", branch_name)

    bump(version: next_version_snapshot)

    sh("git", "commit", "-am", "Preparing for next version")
    push_to_git_remote(
      remote: "origin",
      local_branch: branch_name,
      remote_branch: branch_name,
    )

    create_pull_request(
      repo: "revenuecat/purchases-android",
      title: "Prepare next version: #{next_version_snapshot}",
      base: "main",
      api_token: ENV["GITHUB_TOKEN"],
      head: branch_name
    )
  end

  desc "Build and run purchases module load shedder integration tests"
  desc "This requires the google cloud cli to be installed and initialized."
  lane :run_load_shedder_purchases_integration_tests do |options|
    begin
      google_project_id = ENV['GOOGLE_PROJECT_ID'] || UI.user_error!('Google project id not found.')
      build_purchases_integration_tests(
        app_name: 'loadShedderIntegrationTest',
        api_key: ENV['LOAD_SHEDDER_REVENUECAT_API_KEY'],
        google_purchase_token: ENV['LOAD_SHEDDER_GOOGLE_PURCHASE_TOKEN'],
        product_id_to_purchase: ENV['LOAD_SHEDDER_PRODUCT_ID_TO_PURCHASE'],
        active_entitlements_to_verify: ENV['LOAD_SHEDDER_ACTIVE_ENTITLEMENTS_TO_VERIFY'] || ''
      )

      # We run the test on google firebase test labs
      sh "gcloud firebase test android run --type instrumentation \
            --app ../purchases/test_artifacts/loadShedderIntegrationTest-app.apk \
            --test ../purchases/test_artifacts/loadShedderIntegrationTest-test.apk \
            --timeout 2m \
            --device model=panther,version=33,locale=en,orientation=portrait \
            --results-bucket cloud-test-#{google_project_id}"

      dir_path = File.join(Dir.home, 'gsutil')
      FileUtils.mkdir_p(dir_path)
      # We copy the test results from google cloud to the ~/gsutil folder. We use the tail -1 to get the latest
      sh "gsutil -m cp -r -U `gsutil ls gs://cloud-test-#{google_project_id} | tail -1` ~/gsutil/ | true"
    rescue => exception
      send_slack_load_shedder_integration_test(success: false)
      raise
    else
      send_slack_load_shedder_integration_test(success: true)
    end
  end

  def build_purchases_integration_tests(app_name:, api_key:, google_purchase_token:, product_id_to_purchase:,
                                        active_entitlements_to_verify:, proxy_url: nil, build_type: 'debug')
    constants_path = '../purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt'
    replace_text_in_files(
      previous_text: "REVENUECAT_API_KEY",
      new_text: api_key,
      paths_of_files_to_update: [constants_path]
    )
    replace_text_in_files(
      previous_text: "GOOGLE_PURCHASE_TOKEN",
      new_text: google_purchase_token,
      paths_of_files_to_update: [constants_path]
    )
    replace_text_in_files(
      previous_text: "PRODUCT_ID_TO_PURCHASE",
      new_text: product_id_to_purchase,
      paths_of_files_to_update: [constants_path]
    )
    replace_text_in_files(
      previous_text: "ACTIVE_ENTITLEMENT_IDS_TO_VERIFY",
      new_text: active_entitlements_to_verify,
      paths_of_files_to_update: [constants_path]
    )
    unless proxy_url.nil?
      replace_text_in_files(
        previous_text: "NO_PROXY_URL",
        new_text: proxy_url,
        paths_of_files_to_update: [constants_path]
      )
    end

    # We need to build the same apk twice since firebase test labs don't allow the app and test apks
    # to have same package name

    # Build test apk
    build_purchases_android_test_apk("com.revenuecat.purchases.integrationtests.test", "#{app_name}-app", build_type)

    # Build app apk
    build_purchases_android_test_apk("com.revenuecat.purchases.integrationtests", "#{app_name}-test", build_type)
  end

  lane :send_slack_load_shedder_integration_test do |options|
    success = options[:success] || false
    message =
        if success
            "Android load shedder integration tests V4 finished successfully"
        else
            "Android load shedder integration tests V4 failed"
        end
    slack(
      message: message,
      slack_url: ENV["SLACK_URL_LOAD_SHEDDER_INTEGRATION_TESTS"],
      success: success,
      default_payloads: [:git_branch]
    )
  end
end

def increment_version_in(previous_version, new_version, path)
  sed_regex = 's/' + previous_version + '/' + new_version + '/'
  backup_extension = '.bck'
  sh "sed -i'#{backup_extension}' #{sed_regex} #{path}"
end

def attach_changelog_to_main(options)
  version_number = options[:version]
  current_changelog = File.open("../CHANGELOG.latest.md", 'r')
  master_changelog = File.open("../CHANGELOG.md", 'r')

  current_changelog_data = current_changelog.read
  master_changelog_data = master_changelog.read

  current_changelog.close
  master_changelog.close

  File.open("../CHANGELOG.md", 'w') { |master_changelog_write_mode|
    version_header = "## #{version_number}"
    whole_file_data = "#{version_header}\n\n#{current_changelog_data}\n#{master_changelog_data}"
    puts "going to save. Contents - #{whole_file_data}"
    master_changelog_write_mode.write(whole_file_data)
  }
end

def is_snapshot_version?(version_name)
  version_name.end_with?("-SNAPSHOT")
end

def replace_text_in_files(previous_text:, new_text:, paths_of_files_to_update:)
  paths_of_files_to_update.each do |path|
    sh "sed -i 's/#{previous_text}/#{new_text}/g' #{path}"
  end
end

def build_purchases_android_test_apk(package_name, apk_name, build_type)
  gradle(
    task: ':purchases:assembleAndroidTest',
    properties: {
      "testApplicationId" => package_name,
      "testBuildType" => build_type
    }
  )
  apk_path = "../purchases/build/outputs/apk/androidTest/integrationTest/#{build_type}/purchases-integrationTest-#{build_type}-androidTest.apk"
  new_apk_path = "../purchases/build/outputs/apk/androidTest/integrationTest/#{build_type}/#{apk_name}.apk"
  sh "mv #{apk_path} #{new_apk_path}"
  copy_artifacts(
    target_path: 'purchases/test_artifacts',
    artifacts: ['purchases/build/**/*.apk'],
    fail_on_missing: true
  )
end
