package com.revenuecat.purchases.fbepoc

import com.revenuecat.purchases.fbepoc.models.DummyRequest
import com.revenuecat.purchases.fbepoc.models.DummyResponse
import com.revenuecat.purchases.fbepoc.models.Header
import com.revenuecat.purchases.fbepoc.models.HttpMethod
import com.revenuecat.purchases.fbepoc.models.ResponseStatus
import com.revenuecat.purchases.fbepoc.models.fbe.DummyRequestModel
import com.revenuecat.purchases.fbepoc.models.fbe.DummyResponseModel
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test

/**
 * Proof of concept evaluating FastBinaryEncoding (FBE) for encoding/decoding HTTP-shaped payloads.
 *
 * The models under [com.revenuecat.purchases.fbepoc.models] and the FBE runtime under
 * [com.revenuecat.purchases.fbepoc.fbe] are generated by the `fbec` compiler from `poc.fbe`.
 * See the README in this package for how to regenerate them.
 *
 * These tests demonstrate the core capability we want to evaluate: serialize a domain object to a
 * compact binary buffer and deserialize it back losslessly.
 */
class FbeProofOfConceptTest {

    @Test
    fun `request round-trips through FBE binary buffer`() {
        val request = DummyRequest(
            id = 42,
            method = HttpMethod.post,
            path = "/v1/subscribers/abc123/receipts",
            headers = arrayListOf(
                Header("Authorization", "Bearer sk_test_123"),
                Header("X-Platform", "android"),
            ),
            body = """{"fetch_token":"token","product_id":"premium"}""",
            createdAt = 1_717_000_000_000L,
        )

        // Encode
        val writer = DummyRequestModel()
        val written = writer.serialize(request)
        assertThat(writer.verify()).isTrue()
        assertThat(written).isGreaterThan(0L)
        val bytes = writer.buffer.data.copyOf(writer.buffer.size.toInt())

        // Decode into a fresh model from the raw bytes
        val reader = DummyRequestModel()
        reader.attach(bytes)
        assertThat(reader.verify()).isTrue()
        val decoded = reader.deserialize()

        assertThat(decoded.id).isEqualTo(request.id)
        assertThat(decoded.method).isEqualTo(request.method)
        assertThat(decoded.path).isEqualTo(request.path)
        assertThat(decoded.body).isEqualTo(request.body)
        assertThat(decoded.createdAt).isEqualTo(request.createdAt)
        assertThat(decoded.headers.map { it.name to it.value })
            .containsExactly("Authorization" to "Bearer sk_test_123", "X-Platform" to "android")
    }

    @Test
    fun `response round-trips and optional + empty collections are preserved`() {
        val response = DummyResponse(
            id = 42,
            status = ResponseStatus.ok,
            headers = arrayListOf(Header("Content-Type", "application/json")),
            body = """{"subscriber":{"entitlements":{}}}""",
            elapsedMs = 12.5,
            cached = true,
        )

        val writer = DummyResponseModel()
        writer.serialize(response)
        assertThat(writer.verify()).isTrue()
        val bytes = writer.buffer.data.copyOf(writer.buffer.size.toInt())

        val reader = DummyResponseModel()
        reader.attach(bytes)
        assertThat(reader.verify()).isTrue()
        val decoded = reader.deserialize()

        assertThat(decoded.id).isEqualTo(response.id)
        assertThat(decoded.status).isEqualTo(response.status)
        assertThat(decoded.body).isEqualTo(response.body)
        assertThat(decoded.elapsedMs).isEqualTo(12.5)
        assertThat(decoded.cached).isTrue()
        assertThat(decoded.headers.single().name).isEqualTo("Content-Type")
    }

    @Test
    fun `null optional body is preserved`() {
        val request = DummyRequest(
            id = 1,
            method = HttpMethod.get,
            path = "/v1/subscribers/abc123",
            headers = arrayListOf(),
            body = null,
            createdAt = 0L,
        )

        val writer = DummyRequestModel()
        writer.serialize(request)
        val bytes = writer.buffer.data.copyOf(writer.buffer.size.toInt())

        val reader = DummyRequestModel()
        reader.attach(bytes)
        val decoded = reader.deserialize()

        assertThat(decoded.body).isNull()
        assertThat(decoded.headers).isEmpty()
    }

    @Test
    fun `binary payload is smaller than the equivalent JSON for this model`() {
        val request = DummyRequest(
            id = 42,
            method = HttpMethod.post,
            path = "/v1/subscribers/abc123/receipts",
            headers = arrayListOf(
                Header("Authorization", "Bearer sk_test_123"),
                Header("X-Platform", "android"),
            ),
            body = """{"fetch_token":"token","product_id":"premium"}""",
            createdAt = 1_717_000_000_000L,
        )

        val writer = DummyRequestModel()
        writer.serialize(request)
        val fbeSize = writer.buffer.size

        // Rough JSON equivalent for a like-for-like size comparison.
        val json = """
            {"id":42,"method":"post","path":"/v1/subscribers/abc123/receipts",
            "headers":[{"name":"Authorization","value":"Bearer sk_test_123"},
            {"name":"X-Platform","value":"android"}],
            "body":"{\"fetch_token\":\"token\",\"product_id\":\"premium\"}",
            "createdAt":1717000000000}
        """.trimIndent().replace("\n", "")
        val jsonSize = json.toByteArray(Charsets.UTF_8).size

        println("FBE binary size: $fbeSize bytes; JSON size: $jsonSize bytes")
        assertThat(fbeSize).isLessThan(jsonSize.toLong())
    }
}
