package com.revenuecat.purchases.fbepoc

import com.revenuecat.purchases.fbepoc.payload.Payload
import com.revenuecat.purchases.fbepoc.payload.fbe.PayloadModel
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test
import java.util.Base64
import java.util.TreeMap

/**
 * Proof of concept evaluating FastBinaryEncoding (FBE) for encoding/decoding HTTP-shaped payloads.
 *
 * The model under [com.revenuecat.purchases.fbepoc.payload] and the FBE runtime under
 * [com.revenuecat.purchases.fbepoc.fbe] are generated by the `fbec` compiler from `poc.fbe`.
 * See the README in this package for how to regenerate them.
 *
 * The schema is a single `Payload { bytes config; bytes<bytes> blobs; }`, exercising a raw byte
 * field and a bytes-keyed map.
 */
class FbeProofOfConceptTest {

    // The generated map is a java.util.TreeMap<ByteArray, ByteArray>, but ByteArray is not
    // Comparable, so a natural-ordering TreeMap throws once it holds more than one key. We supply an
    // explicit unsigned-lexicographic comparator wherever we build one of these maps.
    private val byteArrayComparator = Comparator<ByteArray> { a, b ->
        val shared = minOf(a.size, b.size)
        for (i in 0 until shared) {
            val cmp = (a[i].toInt() and 0xFF).compareTo(b[i].toInt() and 0xFF)
            if (cmp != 0) return@Comparator cmp
        }
        a.size.compareTo(b.size)
    }

    private fun blobs(vararg entries: Pair<ByteArray, ByteArray>): TreeMap<ByteArray, ByteArray> =
        TreeMap<ByteArray, ByteArray>(byteArrayComparator).apply {
            entries.forEach { (key, value) -> put(key, value) }
        }

    @Test
    fun `payload round-trips config and a multi-entry blobs map`() {
        val payload = Payload(
            config = byteArrayOf(0x01, 0x02, 0x03, 0x7F, -1),
            blobs = blobs(
                "etag".toByteArray() to "W/\"abc123\"".toByteArray(),
                "cache-key".toByteArray() to byteArrayOf(0xDE.toByte(), 0xAD.toByte(), 0xBE.toByte(), 0xEF.toByte()),
            ),
        )

        // Encode
        val writer = PayloadModel()
        val written = writer.serialize(payload)
        assertThat(writer.verify()).isTrue()
        assertThat(written).isGreaterThan(0L)
        val bytes = writer.buffer.data.copyOf(writer.buffer.size.toInt())

        // Decode into a target whose blobs map carries the comparator. The no-arg deserialize()
        // builds a default TreeMap() and would throw on a multi-entry ByteArray-keyed map.
        val reader = PayloadModel()
        reader.attach(bytes)
        assertThat(reader.verify()).isTrue()
        val decoded = Payload(blobs = TreeMap(byteArrayComparator))
        reader.deserialize(decoded)

        assertThat(decoded.config).isEqualTo(payload.config)
        assertThat(decoded.blobs).hasSize(2)
        // Lookups use the comparator, so equal-content keys match.
        assertThat(decoded.blobs["etag".toByteArray()]).isEqualTo("W/\"abc123\"".toByteArray())
        assertThat(decoded.blobs["cache-key".toByteArray()])
            .isEqualTo(byteArrayOf(0xDE.toByte(), 0xAD.toByte(), 0xBE.toByte(), 0xEF.toByte()))
    }

    @Test
    fun `payload round-trips with an empty blobs map via no-arg deserialize`() {
        val payload = Payload(
            config = "hello".toByteArray(),
            blobs = blobs(),
        )

        val writer = PayloadModel()
        writer.serialize(payload)
        val bytes = writer.buffer.data.copyOf(writer.buffer.size.toInt())

        val reader = PayloadModel()
        reader.attach(bytes)
        assertThat(reader.verify()).isTrue()
        // Safe for an empty map: the default TreeMap() never compares keys.
        val decoded = reader.deserialize()

        assertThat(decoded.config).isEqualTo("hello".toByteArray())
        assertThat(decoded.blobs).isEmpty()
    }

    @Test
    fun `reports FBE binary size against the equivalent base64 JSON for this model`() {
        val payload = Payload(
            config = byteArrayOf(0x01, 0x02, 0x03, 0x7F, -1),
            blobs = blobs(
                "etag".toByteArray() to "W/\"abc123\"".toByteArray(),
                "cache-key".toByteArray() to byteArrayOf(0xDE.toByte(), 0xAD.toByte(), 0xBE.toByte(), 0xEF.toByte()),
            ),
        )

        val writer = PayloadModel()
        writer.serialize(payload)
        val fbeSize = writer.buffer.size

        // Bytes can't go on the wire as JSON directly; the usual encoding is base64.
        val b64 = Base64.getEncoder()
        val json = buildString {
            append("""{"config":"""").append(b64.encodeToString(payload.config)).append("""","blobs":{""")
            payload.blobs.entries.forEachIndexed { i, e ->
                if (i > 0) append(",")
                append('"').append(b64.encodeToString(e.key)).append("""":"""")
                append(b64.encodeToString(e.value)).append('"')
            }
            append("}}")
        }
        val jsonSize = json.toByteArray(Charsets.UTF_8).size

        // Note: for a tiny, binary-heavy payload like this, FBE is not necessarily smaller than
        // base64 JSON. FBE's per-field and per-map-entry framing (4-byte offsets + 4-byte sizes)
        // is fixed overhead that only pays off as payloads grow. We report both rather than assert
        // a direction that does not hold at this size.
        println("FBE binary size: $fbeSize bytes; base64-JSON size: $jsonSize bytes")
        assertThat(fbeSize).isGreaterThan(0L)
        assertThat(jsonSize).isGreaterThan(0)
    }
}
