#!/usr/bin/env bash
#
# Regenerates the committed FlatBuffers Kotlin accessors for the PoC.
#
# flatc emits one class per file with BOTH read accessors and write (FlatBufferBuilder) helpers.
# We split each into two flavors via scripts/flatbuffers_postprocess.py:
#
#   * main  -> reader-only accessors shipped by the SDK, under
#              purchases/src/main/kotlin/.../flatbuffers/generated. These drop every
#              com.google.flatbuffers import and bind to the VENDORED, package-private runtime
#              committed under purchases/src/main/java/.../flatbuffers/generated (Table, Constants,
#              Utf8*). The shipped AAR therefore contains NO com.google.flatbuffers code.
#   * test  -> full read+write accessors under purchases/src/test/java/.../flatbuffers/testgen,
#              bound to the real com.google.flatbuffers runtime (a test-only dependency). The
#              encoder fixture (the "backend side") uses these.
#
# The generated code pins the runtime version (Constants.FLATBUFFERS_<version>), so the flatc
# compiler version MUST match the `flatbuffers` version in gradle/libs.versions.toml. That same
# version also governs the vendored runtime and the test-only dependency. Generating with a
# mismatched flatc produces code that will not compile.
#
# The vendored .java runtime under src/main/java/.../generated is maintained separately and is
# NOT regenerated by this script.
#
# Usage: ./scripts/generate-flatbuffers.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA="$REPO_ROOT/purchases/src/flatbuffers/schema/payload.fbs"
MAIN_GEN_DIR="$REPO_ROOT/purchases/src/main/kotlin/com/revenuecat/purchases/flatbuffers/generated"
TEST_GEN_DIR="$REPO_ROOT/purchases/src/test/java/com/revenuecat/purchases/flatbuffers/testgen"
POSTPROCESS="$REPO_ROOT/scripts/flatbuffers_postprocess.py"
EXPECTED_VERSION="$(grep -E '^flatbuffers = ' "$REPO_ROOT/gradle/libs.versions.toml" | sed -E 's/.*"([^"]+)".*/\1/')"

if ! command -v flatc >/dev/null 2>&1; then
  echo "error: flatc not found. Install it (e.g. 'brew install flatbuffers') at version $EXPECTED_VERSION." >&2
  exit 1
fi

ACTUAL_VERSION="$(flatc --version | sed -E 's/flatc version ([0-9.]+).*/\1/')"
if [ "$ACTUAL_VERSION" != "$EXPECTED_VERSION" ]; then
  echo "error: flatc version mismatch. Expected $EXPECTED_VERSION (from libs.versions.toml), found $ACTUAL_VERSION." >&2
  echo "       Generated code pins the runtime version and will not compile if these differ." >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Generating Kotlin accessors with flatc $ACTUAL_VERSION ..."
flatc --kotlin -o "$TMP_DIR" "$SCHEMA"
RAW_DIR="$TMP_DIR/com/revenuecat/purchases/flatbuffers/generated"

mkdir -p "$MAIN_GEN_DIR" "$TEST_GEN_DIR"
for raw in "$RAW_DIR"/*.kt; do
  name="$(basename "$raw")"
  python3 "$POSTPROCESS" main < "$raw" > "$MAIN_GEN_DIR/$name"
  python3 "$POSTPROCESS" test < "$raw" > "$TEST_GEN_DIR/$name"
  echo "  $name -> generated/ (reader-only) + testgen/ (full)"
done

echo "Done."
echo "Reminder: the vendored runtime under src/main/java/.../flatbuffers/generated (Table.java,"
echo "Constants.java, Utf8*.java) is maintained separately and was NOT regenerated."
