package com.revenuecat.purchases.common.diagnostics

enum class DiagnosticsEventName {
    HTTP_REQUEST_PERFORMED,
    MAX_EVENTS_STORED_LIMIT_REACHED,
    GOOGLE_QUERY_PRODUCT_DETAILS_REQUEST,
    GOOGLE_QUERY_PURCHASES_REQUEST,
    GOOGLE_QUERY_PURCHASE_HISTORY_REQUEST,
}
