//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models.fbe

// Fast Binary Encoding DummyRequest field model
@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods", "ReplaceGetOrSet")
internal class FieldModelDummyRequest(buffer: com.revenuecat.purchases.fbepoc.fbe.Buffer, offset: Long) : com.revenuecat.purchases.fbepoc.fbe.FieldModel(buffer, offset)
{
    val id: com.revenuecat.purchases.fbepoc.fbe.FieldModelInt32 = com.revenuecat.purchases.fbepoc.fbe.FieldModelInt32(buffer, 4 + 4)
    val method: FieldModelHttpMethod = FieldModelHttpMethod(buffer, id.fbeOffset + id.fbeSize)
    val path: com.revenuecat.purchases.fbepoc.fbe.FieldModelString = com.revenuecat.purchases.fbepoc.fbe.FieldModelString(buffer, method.fbeOffset + method.fbeSize)
    val headers: FieldModelVectorHeader = FieldModelVectorHeader(buffer, path.fbeOffset + path.fbeSize)
    val body: FieldModelOptionalString = FieldModelOptionalString(buffer, headers.fbeOffset + headers.fbeSize)
    val createdAt: com.revenuecat.purchases.fbepoc.fbe.FieldModelInt64 = com.revenuecat.purchases.fbepoc.fbe.FieldModelInt64(buffer, body.fbeOffset + body.fbeSize)

    // Field size
    override val fbeSize: Long = 4

    // Field body size
    val fbeBody: Long = (4 + 4
        + id.fbeSize
        + method.fbeSize
        + path.fbeSize
        + headers.fbeSize
        + body.fbeSize
        + createdAt.fbeSize
        )

    // Field extra size
    override val fbeExtra: Long get()
    {
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return 0

        val fbeStructOffset = readUInt32(fbeOffset).toLong()
        if ((fbeStructOffset == 0L) || ((_buffer.offset + fbeStructOffset + 4) > _buffer.size))
            return 0

        _buffer.shift(fbeStructOffset)

        val fbeResult = (fbeBody
            + id.fbeExtra
            + method.fbeExtra
            + path.fbeExtra
            + headers.fbeExtra
            + body.fbeExtra
            + createdAt.fbeExtra
            )

        _buffer.unshift(fbeStructOffset)

        return fbeResult
    }

    // Field type
    var fbeType: Long = fbeTypeConst

    companion object
    {
        const val fbeTypeConst: Long = 2
    }

    // Check if the struct value is valid
    fun verify(fbeVerifyType: Boolean = true): Boolean
    {
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return true

        val fbeStructOffset = readUInt32(fbeOffset).toLong()
        if ((fbeStructOffset == 0L) || ((_buffer.offset + fbeStructOffset + 4 + 4) > _buffer.size))
            return false

        val fbeStructSize = readUInt32(fbeStructOffset).toLong()
        if (fbeStructSize < (4 + 4))
            return false

        val fbeStructType = readUInt32(fbeStructOffset + 4).toLong()
        if (fbeVerifyType && (fbeStructType != fbeType))
            return false

        _buffer.shift(fbeStructOffset)
        val fbeResult = verifyFields(fbeStructSize)
        _buffer.unshift(fbeStructOffset)
        return fbeResult
    }

    // Check if the struct fields are valid
    @Suppress("UNUSED_PARAMETER")
    fun verifyFields(fbeStructSize: Long): Boolean
    {
        var fbeCurrentSize = 4L + 4L

        if ((fbeCurrentSize + id.fbeSize) > fbeStructSize)
            return true
        if (!id.verify())
            return false
        fbeCurrentSize += id.fbeSize

        if ((fbeCurrentSize + method.fbeSize) > fbeStructSize)
            return true
        if (!method.verify())
            return false
        fbeCurrentSize += method.fbeSize

        if ((fbeCurrentSize + path.fbeSize) > fbeStructSize)
            return true
        if (!path.verify())
            return false
        fbeCurrentSize += path.fbeSize

        if ((fbeCurrentSize + headers.fbeSize) > fbeStructSize)
            return true
        if (!headers.verify())
            return false
        fbeCurrentSize += headers.fbeSize

        if ((fbeCurrentSize + body.fbeSize) > fbeStructSize)
            return true
        if (!body.verify())
            return false
        fbeCurrentSize += body.fbeSize

        if ((fbeCurrentSize + createdAt.fbeSize) > fbeStructSize)
            return true
        if (!createdAt.verify())
            return false
        fbeCurrentSize += createdAt.fbeSize

        return true
    }

    // Get the struct value (begin phase)
    fun getBegin(): Long
    {
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return 0

        val fbeStructOffset = readUInt32(fbeOffset).toLong()
        assert((fbeStructOffset > 0) && ((_buffer.offset + fbeStructOffset + 4 + 4) <= _buffer.size)) { "Model is broken!" }
        if ((fbeStructOffset == 0L) || ((_buffer.offset + fbeStructOffset + 4 + 4) > _buffer.size))
            return 0

        val fbeStructSize = readUInt32(fbeStructOffset).toLong()
        assert(fbeStructSize >= (4 + 4)) { "Model is broken!" }
        if (fbeStructSize < (4 + 4))
            return 0

        _buffer.shift(fbeStructOffset)
        return fbeStructOffset
    }

    // Get the struct value (end phase)
    fun getEnd(fbeBegin: Long)
    {
        _buffer.unshift(fbeBegin)
    }

    // Get the struct value
    fun get(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyRequest = com.revenuecat.purchases.fbepoc.models.DummyRequest()): com.revenuecat.purchases.fbepoc.models.DummyRequest
    {
        val fbeBegin = getBegin()
        if (fbeBegin == 0L)
            return fbeValue

        val fbeStructSize = readUInt32(0).toLong()
        getFields(fbeValue, fbeStructSize)
        getEnd(fbeBegin)
        return fbeValue
    }

    // Get the struct fields values
    @Suppress("UNUSED_PARAMETER")
    fun getFields(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyRequest, fbeStructSize: Long)
    {
        var fbeCurrentSize = 4L + 4L

        if ((fbeCurrentSize + id.fbeSize) <= fbeStructSize)
            fbeValue.id = id.get()
        else
            fbeValue.id = 0
        fbeCurrentSize += id.fbeSize

        if ((fbeCurrentSize + method.fbeSize) <= fbeStructSize)
            fbeValue.method = method.get()
        else
            fbeValue.method = com.revenuecat.purchases.fbepoc.models.HttpMethod()
        fbeCurrentSize += method.fbeSize

        if ((fbeCurrentSize + path.fbeSize) <= fbeStructSize)
            fbeValue.path = path.get()
        else
            fbeValue.path = ""
        fbeCurrentSize += path.fbeSize

        if ((fbeCurrentSize + headers.fbeSize) <= fbeStructSize)
            headers.get(fbeValue.headers)
        else
            fbeValue.headers.clear()
        fbeCurrentSize += headers.fbeSize

        if ((fbeCurrentSize + body.fbeSize) <= fbeStructSize)
            fbeValue.body = body.get()
        else
            fbeValue.body = null
        fbeCurrentSize += body.fbeSize

        if ((fbeCurrentSize + createdAt.fbeSize) <= fbeStructSize)
            fbeValue.createdAt = createdAt.get()
        else
            fbeValue.createdAt = 0L
        fbeCurrentSize += createdAt.fbeSize
    }

    // Set the struct value (begin phase)
    fun setBegin(): Long
    {
        assert((_buffer.offset + fbeOffset + fbeSize) <= _buffer.size) { "Model is broken!" }
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return 0

        val fbeStructSize = fbeBody
        val fbeStructOffset = _buffer.allocate(fbeStructSize) - _buffer.offset
        assert((fbeStructOffset > 0) && ((_buffer.offset + fbeStructOffset + fbeStructSize) <= _buffer.size)) { "Model is broken!" }
        if ((fbeStructOffset <= 0) || ((_buffer.offset + fbeStructOffset + fbeStructSize) > _buffer.size))
            return 0

        write(fbeOffset, fbeStructOffset.toUInt())
        write(fbeStructOffset, fbeStructSize.toUInt())
        write(fbeStructOffset + 4, fbeType.toUInt())

        _buffer.shift(fbeStructOffset)
        return fbeStructOffset
    }

    // Set the struct value (end phase)
    fun setEnd(fbeBegin: Long)
    {
        _buffer.unshift(fbeBegin)
    }

    // Set the struct value
    fun set(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyRequest)
    {
        val fbeBegin = setBegin()
        if (fbeBegin == 0L)
            return

        setFields(fbeValue)
        setEnd(fbeBegin)
    }

    // Set the struct fields values
    @Suppress("UNUSED_PARAMETER")
    fun setFields(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyRequest)
    {
        id.set(fbeValue.id)
        method.set(fbeValue.method)
        path.set(fbeValue.path)
        headers.set(fbeValue.headers)
        body.set(fbeValue.body)
        createdAt.set(fbeValue.createdAt)
    }
}
