//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models.fbe

// Fast Binary Encoding HttpMethod field model
internal class FieldModelHttpMethod(buffer: com.revenuecat.purchases.fbepoc.fbe.Buffer, offset: Long) : com.revenuecat.purchases.fbepoc.fbe.FieldModel(buffer, offset)
{
    // Field size
    override val fbeSize: Long = 1

    // Get the value
    fun get(defaults: com.revenuecat.purchases.fbepoc.models.HttpMethod = com.revenuecat.purchases.fbepoc.models.HttpMethod()): com.revenuecat.purchases.fbepoc.models.HttpMethod
    {
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return defaults

        return com.revenuecat.purchases.fbepoc.models.HttpMethod(readByte(fbeOffset))
    }

    // Set the value
    fun set(value: com.revenuecat.purchases.fbepoc.models.HttpMethod)
    {
        assert((_buffer.offset + fbeOffset + fbeSize) <= _buffer.size) { "Model is broken!" }
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return

        write(fbeOffset, value.raw)
    }
}
