//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: poc.fbe
// FBE version: 1.15.0.0
//------------------------------------------------------------------------------

@file:Suppress("UnusedImport", "unused")

package com.revenuecat.purchases.fbepoc.models.fbe

// Fast Binary Encoding DummyResponse field model
@Suppress("MemberVisibilityCanBePrivate", "RemoveRedundantCallsOfConversionMethods", "ReplaceGetOrSet")
internal class FieldModelDummyResponse(buffer: com.revenuecat.purchases.fbepoc.fbe.Buffer, offset: Long) : com.revenuecat.purchases.fbepoc.fbe.FieldModel(buffer, offset)
{
    val id: com.revenuecat.purchases.fbepoc.fbe.FieldModelInt32 = com.revenuecat.purchases.fbepoc.fbe.FieldModelInt32(buffer, 4 + 4)
    val status: FieldModelResponseStatus = FieldModelResponseStatus(buffer, id.fbeOffset + id.fbeSize)
    val headers: FieldModelVectorHeader = FieldModelVectorHeader(buffer, status.fbeOffset + status.fbeSize)
    val body: com.revenuecat.purchases.fbepoc.fbe.FieldModelString = com.revenuecat.purchases.fbepoc.fbe.FieldModelString(buffer, headers.fbeOffset + headers.fbeSize)
    val elapsedMs: com.revenuecat.purchases.fbepoc.fbe.FieldModelDouble = com.revenuecat.purchases.fbepoc.fbe.FieldModelDouble(buffer, body.fbeOffset + body.fbeSize)
    val cached: com.revenuecat.purchases.fbepoc.fbe.FieldModelBoolean = com.revenuecat.purchases.fbepoc.fbe.FieldModelBoolean(buffer, elapsedMs.fbeOffset + elapsedMs.fbeSize)

    // Field size
    override val fbeSize: Long = 4

    // Field body size
    val fbeBody: Long = (4 + 4
        + id.fbeSize
        + status.fbeSize
        + headers.fbeSize
        + body.fbeSize
        + elapsedMs.fbeSize
        + cached.fbeSize
        )

    // Field extra size
    override val fbeExtra: Long get()
    {
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return 0

        val fbeStructOffset = readUInt32(fbeOffset).toLong()
        if ((fbeStructOffset == 0L) || ((_buffer.offset + fbeStructOffset + 4) > _buffer.size))
            return 0

        _buffer.shift(fbeStructOffset)

        val fbeResult = (fbeBody
            + id.fbeExtra
            + status.fbeExtra
            + headers.fbeExtra
            + body.fbeExtra
            + elapsedMs.fbeExtra
            + cached.fbeExtra
            )

        _buffer.unshift(fbeStructOffset)

        return fbeResult
    }

    // Field type
    var fbeType: Long = fbeTypeConst

    companion object
    {
        const val fbeTypeConst: Long = 3
    }

    // Check if the struct value is valid
    fun verify(fbeVerifyType: Boolean = true): Boolean
    {
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return true

        val fbeStructOffset = readUInt32(fbeOffset).toLong()
        if ((fbeStructOffset == 0L) || ((_buffer.offset + fbeStructOffset + 4 + 4) > _buffer.size))
            return false

        val fbeStructSize = readUInt32(fbeStructOffset).toLong()
        if (fbeStructSize < (4 + 4))
            return false

        val fbeStructType = readUInt32(fbeStructOffset + 4).toLong()
        if (fbeVerifyType && (fbeStructType != fbeType))
            return false

        _buffer.shift(fbeStructOffset)
        val fbeResult = verifyFields(fbeStructSize)
        _buffer.unshift(fbeStructOffset)
        return fbeResult
    }

    // Check if the struct fields are valid
    @Suppress("UNUSED_PARAMETER")
    fun verifyFields(fbeStructSize: Long): Boolean
    {
        var fbeCurrentSize = 4L + 4L

        if ((fbeCurrentSize + id.fbeSize) > fbeStructSize)
            return true
        if (!id.verify())
            return false
        fbeCurrentSize += id.fbeSize

        if ((fbeCurrentSize + status.fbeSize) > fbeStructSize)
            return true
        if (!status.verify())
            return false
        fbeCurrentSize += status.fbeSize

        if ((fbeCurrentSize + headers.fbeSize) > fbeStructSize)
            return true
        if (!headers.verify())
            return false
        fbeCurrentSize += headers.fbeSize

        if ((fbeCurrentSize + body.fbeSize) > fbeStructSize)
            return true
        if (!body.verify())
            return false
        fbeCurrentSize += body.fbeSize

        if ((fbeCurrentSize + elapsedMs.fbeSize) > fbeStructSize)
            return true
        if (!elapsedMs.verify())
            return false
        fbeCurrentSize += elapsedMs.fbeSize

        if ((fbeCurrentSize + cached.fbeSize) > fbeStructSize)
            return true
        if (!cached.verify())
            return false
        fbeCurrentSize += cached.fbeSize

        return true
    }

    // Get the struct value (begin phase)
    fun getBegin(): Long
    {
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return 0

        val fbeStructOffset = readUInt32(fbeOffset).toLong()
        assert((fbeStructOffset > 0) && ((_buffer.offset + fbeStructOffset + 4 + 4) <= _buffer.size)) { "Model is broken!" }
        if ((fbeStructOffset == 0L) || ((_buffer.offset + fbeStructOffset + 4 + 4) > _buffer.size))
            return 0

        val fbeStructSize = readUInt32(fbeStructOffset).toLong()
        assert(fbeStructSize >= (4 + 4)) { "Model is broken!" }
        if (fbeStructSize < (4 + 4))
            return 0

        _buffer.shift(fbeStructOffset)
        return fbeStructOffset
    }

    // Get the struct value (end phase)
    fun getEnd(fbeBegin: Long)
    {
        _buffer.unshift(fbeBegin)
    }

    // Get the struct value
    fun get(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyResponse = com.revenuecat.purchases.fbepoc.models.DummyResponse()): com.revenuecat.purchases.fbepoc.models.DummyResponse
    {
        val fbeBegin = getBegin()
        if (fbeBegin == 0L)
            return fbeValue

        val fbeStructSize = readUInt32(0).toLong()
        getFields(fbeValue, fbeStructSize)
        getEnd(fbeBegin)
        return fbeValue
    }

    // Get the struct fields values
    @Suppress("UNUSED_PARAMETER")
    fun getFields(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyResponse, fbeStructSize: Long)
    {
        var fbeCurrentSize = 4L + 4L

        if ((fbeCurrentSize + id.fbeSize) <= fbeStructSize)
            fbeValue.id = id.get()
        else
            fbeValue.id = 0
        fbeCurrentSize += id.fbeSize

        if ((fbeCurrentSize + status.fbeSize) <= fbeStructSize)
            fbeValue.status = status.get()
        else
            fbeValue.status = com.revenuecat.purchases.fbepoc.models.ResponseStatus()
        fbeCurrentSize += status.fbeSize

        if ((fbeCurrentSize + headers.fbeSize) <= fbeStructSize)
            headers.get(fbeValue.headers)
        else
            fbeValue.headers.clear()
        fbeCurrentSize += headers.fbeSize

        if ((fbeCurrentSize + body.fbeSize) <= fbeStructSize)
            fbeValue.body = body.get()
        else
            fbeValue.body = ""
        fbeCurrentSize += body.fbeSize

        if ((fbeCurrentSize + elapsedMs.fbeSize) <= fbeStructSize)
            fbeValue.elapsedMs = elapsedMs.get(0.0)
        else
            fbeValue.elapsedMs = 0.0
        fbeCurrentSize += elapsedMs.fbeSize

        if ((fbeCurrentSize + cached.fbeSize) <= fbeStructSize)
            fbeValue.cached = cached.get(false)
        else
            fbeValue.cached = false
        fbeCurrentSize += cached.fbeSize
    }

    // Set the struct value (begin phase)
    fun setBegin(): Long
    {
        assert((_buffer.offset + fbeOffset + fbeSize) <= _buffer.size) { "Model is broken!" }
        if ((_buffer.offset + fbeOffset + fbeSize) > _buffer.size)
            return 0

        val fbeStructSize = fbeBody
        val fbeStructOffset = _buffer.allocate(fbeStructSize) - _buffer.offset
        assert((fbeStructOffset > 0) && ((_buffer.offset + fbeStructOffset + fbeStructSize) <= _buffer.size)) { "Model is broken!" }
        if ((fbeStructOffset <= 0) || ((_buffer.offset + fbeStructOffset + fbeStructSize) > _buffer.size))
            return 0

        write(fbeOffset, fbeStructOffset.toUInt())
        write(fbeStructOffset, fbeStructSize.toUInt())
        write(fbeStructOffset + 4, fbeType.toUInt())

        _buffer.shift(fbeStructOffset)
        return fbeStructOffset
    }

    // Set the struct value (end phase)
    fun setEnd(fbeBegin: Long)
    {
        _buffer.unshift(fbeBegin)
    }

    // Set the struct value
    fun set(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyResponse)
    {
        val fbeBegin = setBegin()
        if (fbeBegin == 0L)
            return

        setFields(fbeValue)
        setEnd(fbeBegin)
    }

    // Set the struct fields values
    @Suppress("UNUSED_PARAMETER")
    fun setFields(fbeValue: com.revenuecat.purchases.fbepoc.models.DummyResponse)
    {
        id.set(fbeValue.id)
        status.set(fbeValue.status)
        headers.set(fbeValue.headers)
        body.set(fbeValue.body)
        elapsedMs.set(fbeValue.elapsedMs)
        cached.set(fbeValue.cached)
    }
}
